GameZone/Models/BaseEntity.cs
namespace GameZone.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }

        [MaxLength(250)]
        public string Name { get; set; } = string.Empty;
    }
}

GameZone/Models/Category.cs
namespace GameZone.Models
{
    public class Category : BaseEntity
    {
        // Navigation property ( one-to-many relationship)
        public ICollection<Game> Games { get; set; } = [];
    }
}

GameZone/Models/Device.cs
namespace GameZone.Models
{
    public class Device : BaseEntity
    {
        [MaxLength(50)]
        public string Icon { get; set; } = string.Empty;
    }
}

GameZone/Models/ErrorViewModel.cs
namespace GameZone.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GameZone/Models/Game.cs
namespace GameZone.Models
{
    public class Game : BaseEntity
    {
        [MaxLength(2500)]
        public string Description { get; set; } = string.Empty;

        [MaxLength(500)]
        public string Cover { get; set; } = string.Empty;

        public int CategoryId { get; set; } // Foreign key

        // Navigation property ( one-to-many relationship)
        public Category Category { get; set; } = default!;

        // Navigation property ( many-to-many relationship)
        public ICollection<GameDevice> Devices { get; set; } = [];
    }
}

GameZone/Models/GameDevice.cs
namespace GameZone.Models
{
    public class GameDevice
    {
        public int GameId { get; set; } // Foreign key

        // Navigation property ( many-to-many relationship)
        public Game Game { get; set; } = default!;

        public int DeviceId { get; set; } // Foreign key

        // Navigation property ( many-to-many relationship)
        public Device Device { get; set; } = default!;
    }
}

GameZone/ViewModels/CreateGameFormViewModel.cs
namespace GameZone.ViewModels
{
    public class CreateGameFormViewModel : GameFormViewModel
    {
        [AllowedExtensions(FileSettings.AllowedExtensions),
            MaxFileSize(FileSettings.MaxFileSizeInBytes)]
        public IFormFile Cover { get; set; } = default!;
    }
}

GameZone/ViewModels/EditGameFormViewModel.cs
namespace GameZone.ViewModels
{
    public class EditGameFormViewModel : GameFormViewModel
    {
        public int Id { get; set; }

        public string? CurrentCover { get; set; }

        [AllowedExtensions(FileSettings.AllowedExtensions),
            MaxFileSize(FileSettings.MaxFileSizeInBytes)]
        public IFormFile? Cover { get; set; } = default!;

    }
}

GameZone/ViewModels/GameFormViewModel.cs
namespace GameZone.ViewModels
{
    public class GameFormViewModel
    {
        [MaxLength(250)]
        public string Name { get; set; } = string.Empty;

        [Display(Name = "Category")]
        public int CategoryId { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; } = Enumerable.Empty<SelectListItem>();

        [Display(Name = "Supported Devices")]
        public List<int> SelectedDevices { get; set; } = default!;

        public IEnumerable<SelectListItem> Devices { get; set; } = Enumerable.Empty<SelectListItem>();

        [MaxLength(2500)]
        public string Description { get; set; } = string.Empty;
    }
}

GameZone/Controllers/GamesController.cs
namespace GameZone.Controllers
{
    public class GamesController : Controller
    {
        private readonly ICategoriesService _categoriesService;
        private readonly IDevicesService _devicesService;
        private readonly IGamesService _gamesService;

        public GamesController(ICategoriesService categoriesService, IDevicesService devicesService, IGamesService gamesService)
        {
            _categoriesService = categoriesService;
            _devicesService = devicesService;
            _gamesService = gamesService;
        }

        public IActionResult Index()
        {
            var games = _gamesService.GetAll();
            return View(games);
        }

        public IActionResult Details(int id)
        {
            var game = _gamesService.GetById(id);

            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateGameFormViewModel viewModel = new()
            {
                Categories = _categoriesService.GetSelectListItems(),

                Devices = _devicesService.GetSelectListItems()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGameFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = _categoriesService.GetSelectListItems();

                model.Devices = _devicesService.GetSelectListItems();

                return View(model);
            }

            await _gamesService.Create(model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var game = _gamesService.GetById(id);
            if (game is null)
            {
                return NotFound();
            }

            EditGameFormViewModel viewModel = new()
            {
                Id = id,
                Name = game.Name,
                Description = game.Description,
                CategoryId = game.CategoryId,
                SelectedDevices = game.Devices.Select(d => d.DeviceId).ToList(),
                Categories = _categoriesService.GetSelectListItems(),
                Devices = _devicesService.GetSelectListItems(),
                CurrentCover = game.Cover
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditGameFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = _categoriesService.GetSelectListItems();

                model.Devices = _devicesService.GetSelectListItems();

                return View(model);
            }

            var game = await _gamesService.Update(model);

            if (game is null)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _gamesService.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }
    }
}

GameZone/Controllers/HomeController.cs
using System.Diagnostics;
namespace GameZone.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGamesService _gamesService;

        public HomeController(IGamesService gamesService)
        {
            _gamesService = gamesService;
        }

        public IActionResult Index()
        {
            var games = _gamesService.GetAll();
            return View(games);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GameZone/Views/Games/Create.cshtml
@model CreateGameFormViewModel
@{
    ViewData["Title"] = "Add Game";
}

<h5>
    <i class="bi bi-plus-circle-dotted"></i>
    Add New Game
</h5>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}


<form asp-controller="Games" enctype="multipart/form-data" >
    <div class="row">
        <div class="col-md-6">
            <div>
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger" ></span>    
            </div>
             <div>
                 <label asp-for="CategoryId" class="form-label mt-4"></label>
                 <select class="form-select" asp-for="CategoryId" asp-items="Model.Categories"
                     data-placeholder="Select a category" data-minimum-results-for-search="Infinity" >
                     <option value=""></option>
                 </select>
                 <span asp-validation-for="CategoryId" class="text-danger"></span>
             </div>
            <div class="form-group">
                <label asp-for="SelectedDevices" class="form-label mt-4"></label>
                <select class="form-select" asp-for="SelectedDevices" asp-items="Model.Devices"
                        data-placeholder="Select devices">
                    <option></option>
                </select>
                <span asp-validation-for="SelectedDevices" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Description" class="form-label mt-4"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Description" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Cover" class="form-label mt-4"></label>
                <input type="file" class="form-control" asp-for="Cover" 
                data-rule-extension="@FileSettings.AllowedExtensions.Replace(".", string.Empty)" 
                data-msg-extension="Not Allowed Extension"
                data-rule-filesize="@FileSettings.MaxFileSizeInBytes"
                data-msg-filesize="File size must be less than @(FileSettings.MaxFileSizeInMB)MB" >
                <small class="form-text text-muted">Only @FileSettings.AllowedExtensions files are allowed with max size of @(FileSettings.MaxFileSizeInMB)MB.</small>
                <span asp-validation-for="Cover" class="text-danger d-block" ></span>
            </div>
            <button type="submit" class="btn btn-light text-black mt-4" >Save</button>
        </div>
        <div class="col-md-6 d-flex justify-content-center pt-4 overflow-hidden">
            <img class="cover-preview d-none" alt="Cover" />
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/filesize-validator.js" asp-append-version="true" ></script>
    <script src="~/js/game-form.js" asp-append-version="true"></script>
}

GameZone/Views/Games/Details.cshtml
@model Game

@{
    ViewData["Title"] = Model.Name; 

}

<div class="card border-success rounded-4 mt-5 overflow-hidden">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-md-8 px-5 py-4 d-flex flex-column justify-content-between">
                <div>
                    <h1 class="text-success fw-bolder" >@Model.Name</h1>
                    <span class="badge bg-info fs-5" mb-4>@Model.Category?.Name</span>
                    <p class="fs-5">@Model.Description</p>
                    </div>
                <div>
                    @foreach (var gameDevice in Model.Devices)
                    {
                        <i class="@gameDevice.Device.Icon me-2 fs-1 text-secondary"></i>
                    }
                </div>
            </div>
            <div class="col-md-4">
                <img src="@($"{FileSettings.ImagesPath}/{Model.Cover}")" alt="@Model.Name"
                     class="w-100" />
            </div>
        </div>
    </div>
</div>

GameZone/Views/Games/Edit.cshtml
@model EditGameFormViewModel
@{
    ViewData["Title"] = "Edit Game";
}

<h5>
    <i class="bi bi-plus-circle-dotted"></i>
    Edit Game
</h5>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}


<form asp-controller="Games" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div>
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="CategoryId" class="form-label mt-4"></label>
                <select class="form-select" asp-for="CategoryId" asp-items="Model.Categories"
                        data-placeholder="Select a category" data-minimum-results-for-search="Infinity">
                    <option value=""></option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectedDevices" class="form-label mt-4"></label>
                <select class="form-select" asp-for="SelectedDevices" asp-items="Model.Devices"
                        data-placeholder="Select devices">
                    <option></option>
                </select>
                <span asp-validation-for="SelectedDevices" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Description" class="form-label mt-4"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Cover" class="form-label mt-4"></label>
                <input type="file" class="form-control" asp-for="Cover"
                       data-rule-extension="@FileSettings.AllowedExtensions.Replace(".", string.Empty)"
                       data-msg-extension="Not Allowed Extension"
                       data-rule-filesize="@FileSettings.MaxFileSizeInBytes"
                       data-msg-filesize="File size must be less than @(FileSettings.MaxFileSizeInMB)MB">
                <small class="form-text text-muted">Only @FileSettings.AllowedExtensions files are allowed with max size of @(FileSettings.MaxFileSizeInMB)MB.</small>
                <span asp-validation-for="Cover" class="text-danger d-block"></span>
            </div>
            <button type="submit" class="btn btn-light text-black mt-4">Save</button>
        </div>
        <div class="col-md-6 d-flex justify-content-center pt-4 overflow-hidden">
            <img class="cover-preview" alt="Cover" src="@($"{FileSettings.ImagesPath}/{Model.CurrentCover}")" />
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/filesize-validator.js" asp-append-version="true"></script>
    <script src="~/js/game-form.js" asp-append-version="true"></script>
}

GameZone/Views/Games/Index.cshtml
@model IEnumerable<Game>

@{
    ViewData["Title"] = "Games";
}

<a class="btn btn-secondary btn-lg" asp-action="Create" >
<i class="bi bi-plus-circle-dotted"></i>
Add Game
</a>

@if (!Model.Any())
{
    <div class="alert alert-warning mt-5">
        <h4 class="alert-heading">No games avaliable!</h4>
        <p class="mb-0">No games were added yet.</p>
    </div>
}

else
{
    <div class="mt-5">
        <table class="table table-bordered border-primary">
            <tbody>
                @foreach(var game in Model)
                {
                    <tr class="border-1 border-success">
                        <td>
                            <div class="d-flex">
                                <div class="pe-4">
                                    <img src="@($"{FileSettings.ImagesPath}/{game.Cover}")" alt="@game.Name" 
                                          style="max-width: 90px"/>
                                </div>
                                <div class="d-flex flex-column justify-content-center">
                                    <h4 class="text-light">@game.Name</h4>
                                    <h5>@game.Category.Name</h5>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">
                            <div class="d-flex justify-content-end">
                                <a class="btn btn-info round rounded-3 me-2" asp-action="Edit" asp-route-id="@game.Id">
                                    <i class="bi bi-pencil-fill"></i>
                                </a>
                                <a href="javascript:;" class="btn btn-danger rounded rounded-3 js-delete" data-id="@game.Id">
                                    <i class="bi bi-trash3"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

}

@section Scripts
{
    <script src="~/js/game-index.js" asp-append-version="true"></script>
}

GameZone/Views/Home/Index.cshtml
@model IEnumerable<Game>

@{
    ViewData["Title"] = "Home Page";
}

@if (!Model.Any())
{
    <div class="alert alert-warning mt-5">
        <h4 class="alert-heading">No games avaliable!</h4>
        <p class="mb-0">No games were added yet.</p>
    </div>
}

else
{
    <div class="row mt-5">
        @foreach(var game in Model)
        {
            <div class="col-lg-4 col-md-6">
                <a class="card border-success mb-3 text-decoration-none rounded-3 overflow-hidden" asp-controller="Games" asp-action="Details" asp-route-id="@game.Id">
                    <div class="card-body" style="background-image:url(@($"{FileSettings.ImagesPath}/{game.Cover}")); 
                                background-size: cover; background-position: center; height: 500px;">
                        <div class="d-flex align-items-end h-100">
                            <span class="badge bg-dark rounded-0 fs-3">@game.Category?.Name</span>
                        </div>
                    </div>
                    <div class="card-footer text-muted d-flex justify-content-between align-items-center">
                        <h5>@game.Name</h5>
                        <div>
                            @foreach (var gameDevice in game.Devices)
                            {
                                <i class="@gameDevice.Device.Icon me-2 fs-4"></i>
                            }
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
    
}

GameZone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Game Zone | @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" >
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameZone.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameZone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Games" asp-action="Index">Games</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GameZone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>